# Generated by Django 4.2.20 on 2025-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0003_conversation_antes_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
