# Generated by Django 4.2.20 on 2025-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0005_conversation_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='dificulad_maxima_alcanzada',
            field=models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='media', max_length=10),
        ),
    ]
