# Generated by Django 4.2.20 on 2025-06-23 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FakeCorp', '0006_userprogress_dificulad_maxima_alcanzada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField()),
                ('dificultad', models.CharField(max_length=10)),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.JSONField()),
                ('respuesta_jugador', models.JSONField()),
                ('es_correcta', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
