# Generated by Django 4.2.20 on 2025-06-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0007_respuestadesafio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='dificulad_maxima_alcanzada',
            new_name='dificultad_maxima_alcanzada',
        ),
    ]
