# Generated by Django 4.2.20 on 2025-06-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0008_rename_dificulad_maxima_alcanzada_userprogress_dificultad_maxima_alcanzada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='etapa',
        ),
    ]
