# Generated by Django 4.2.20 on 2025-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0009_remove_useranswer_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
