# Generated by Django 4.2.20 on 2025-07-02 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FakeCorp', '0010_alter_actividad_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField()),
                ('puntaje_preguntas', models.IntegerField()),
                ('puntaje_maximo', models.IntegerField()),
                ('puntaje_tiempo', models.IntegerField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
                ('tiempo_total', models.DurationField()),
                ('dificultades_iniciales', models.JSONField()),
                ('dificultades_finales', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
