# Generated by Django 4.2.20 on 2025-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0011_registrodesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadesafio',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
