# Generated by Django 4.2.20 on 2025-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0012_respuestadesafio_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestadesafio',
            name='respuesta_correcta',
            field=models.JSONField(null=True),
        ),
    ]
