# Generated by Django 4.2.20 on 2025-07-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0014_conversation_antes_comentario_comentariousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadesafio',
            name='image',
            field=models.TextField(default=None, null=True),
        ),
    ]
