# Generated by Django 4.2.20 on 2025-07-17 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FakeCorp', '0015_respuestadesafio_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='RespuestaDesafio',
            new_name='ChallengeAnswer',
        ),
        migrations.RenameModel(
            old_name='RegistroDesafio',
            new_name='ChallengeRecord',
        ),
        migrations.RenameModel(
            old_name='Etapa',
            new_name='Stage',
        ),
        migrations.RenameModel(
            old_name='ComentarioUsuario',
            new_name='UserComment',
        ),
    ]
