# Generated by Django 4.2.20 on 2025-07-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0016_rename_actividad_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='habilidad',
            new_name='desinformation_name',
        ),
    ]
