# Generated by Django 4.2.20 on 2025-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0017_rename_habilidad_stage_desinformation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengerecord',
            old_name='puntaje_tiempo',
            new_name='bonus_score',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='hora_termino',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='dificultades_finales',
            new_name='final_difficulties',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='dificultades_iniciales',
            new_name='initial_difficulties',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='puntaje_maximo',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='puntaje_preguntas',
            new_name='question_score',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='hora_inicio',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='tiempo_total',
            new_name='total_duration',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='puntaje_obtenido',
            new_name='total_score',
        ),
        migrations.RenameField(
            model_name='challengerecord',
            old_name='usuario',
            new_name='user',
        ),
    ]
