# Generated by Django 4.2.20 on 2025-07-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0018_rename_puntaje_tiempo_challengerecord_bonus_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='respuesta_correcta',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='dificultad',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='es_correcta',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='opciones',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='respuesta_jugador',
            new_name='player_answer',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='pregunta',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='puntaje',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='tema',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='challengeanswer',
            old_name='usuario',
            new_name='user',
        ),
    ]
