# Generated by Django 4.2.20 on 2025-07-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0020_rename_numero_actividad_alcanzada_userprogress_activity_number_reached_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='actividad',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='respuesta',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='buena',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='usuario',
            new_name='user',
        ),
    ]
