# Generated by Django 4.2.20 on 2025-07-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0021_rename_actividad_useranswer_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='antes_actividad',
            new_name='before_activity',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='antes_comentario',
            new_name='before_comment',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='final',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='orden_salida',
            new_name='output_order',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='etapa',
            new_name='stage',
        ),
    ]
