# Generated by Django 4.2.20 on 2025-07-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0022_rename_antes_actividad_conversation_before_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='respuesta',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='comentario_correcto',
            new_name='correct_feedback',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='comentario_incorrecto',
            new_name='incorrect_feedback',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='tipo',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='orden_salida',
            new_name='output_order',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='etapa',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='enunciado',
            new_name='statement',
        ),
    ]
