# Generated by Django 4.2.20 on 2025-07-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCorp', '0023_rename_respuesta_activity_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comentario',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='etapa',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='usuario',
            new_name='user',
        ),
    ]
