# Generated by Django 4.2.20 on 2025-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FakeCorp", "0002_actividad_comentario_correcto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="antes_actividad",
            field=models.BooleanField(default=False),
        ),
    ]
